version: '3.7'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        logging:
            options:
                max-size: 10m
                max-file: "3"

    webserver:
        image: eduardofernandezvillazon/docker-airflow-uk-hydro:automatedLaunch
        build:
            context: https://github.com/EduardoFernandezVillazon/Docker_Airflow_Setup_UK_HDE.git
            dockerfile: Dockerfile
            args:
                AIRFLOW_DEPS: "datadog,dask"
                PYTHON_DEPS: "flask_oauthlib>=0.9"
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./plugins:/usr/local/airflow/plugins
            - ./requirements.txt:/requirements.txt
            - ./script/docker_automated_script.sh:/usr/local/airflow/docker_automated_script.sh
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
